crm/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/',include('crm_leads.urls', namespace="leads"))
]

crm_leads/urls.py
from django.urls import path
from .views import lead_create, lead_delete, lead_details, lead_list, lead_update

app_name = "leads"

urlpatterns = [
    path('',lead_list,name="lead-list"),
    path('<int:pk>/',lead_details,name="details"),
    path('<int:pk>/update/',lead_update,name="update"),
    path('<int:pk>/delete/',lead_delete,name="delete"),
    path('new/',lead_create,name="create")
]

crm_leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    '''This Class describes a main atributes for CustomUser model.
     Documentation recomedate to make a AbstractUser inheritance. '''
    pass


class Lead(models.Model):
    '''This Class describes a main atributes for a Lead model and has a dependency 'one to many'. '''
    
    CHOICES = (
        ("VK", "VK"),
        ("YouTube", "YouTube"),
        ("Instagram", "Instagram"),
        ("Twitter", "Twitter"),
    )


    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=18)

    phoned = models.BooleanField(default=False)
    source = models.CharField(choices=CHOICES, max_length=100,blank=True)

    profile_picture = models.ImageField(blank=True, null=True)
    agent = models.ForeignKey("Agent",on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

class Agent(models.Model):
    '''This Class describes a main atributes for Agent model and has 'One to One' dependency. '''
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username

crm_leads/forms.py
from django import forms
from .models import Lead

class ModelLeadForm(forms.ModelForm):
    '''That class allows make a form based on 'Lead' model's attributes'''
    class Meta:
        model = Lead
        fields = '__all__'


class ModelLeadFormUpdate(forms.ModelForm):
    class Meta:
        model = Lead
        fields = '__all__'

crm_leads/views.py
from django.http import HttpRequest, HttpResponseRedirect, QueryDict
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import ModelLeadForm, ModelLeadFormUpdate
from .models import Lead


def lead_list(request:HttpRequest)-> render:
   '''This function shows a list of leads at the page from queryset '''
   context = {
      "leads": Lead.objects.all()
   }
   return render(request,'crm_leads/lead_list.html', context)


def lead_details(request:HttpRequest,pk:int)-> render:
   '''This function shows a list of details about current lead'''
   context = {
      "lead":Lead.objects.get(id=pk)
   }
   return render(request,'crm_leads/lead_details.html',context)


def lead_create(request:QueryDict)->render:
   '''This function renders the page with form to create a new lead'''
   leadform = ModelLeadForm()
   print(request.POST)
   if request.method == "POST":
      print("receiving a POST request...")
      # create a form instance and populate it with data from the request: (from documentation)
      leadform = ModelLeadForm(request.POST)
      if leadform.is_valid():
         print("Your form is passed the validation")
         leadform.save()
         # return HttpResponseRedirect(reverse("lead-list"))
         return redirect('/leads/')
      else:
         leadform = ModelLeadForm()
   return render(request,'crm_leads/lead_create.html',{'leadform':leadform})


def lead_update(request:QueryDict,pk:int)->render:
   '''This function renders the page with form to update an existing lead'''
   lead = Lead.objects.get(id=pk)
   leadform_update = ModelLeadFormUpdate(instance=lead)
   print(request.POST)
   if request.method == "POST":
      print("receiving a POST request...")
      leadform_update = ModelLeadFormUpdate(request.POST,instance=lead)
      if leadform_update.is_valid():
         print("Your form is passed the validation")
         leadform_update.save()
         return redirect(f'/leads/{pk}')
      else:
         leadform_update = ModelLeadFormUpdate()   
   return render(request,'crm_leads/lead_update.html',{'leadform_update':leadform_update,"lead":lead})   


def lead_delete(request:QueryDict,pk:int)->render:
   lead = Lead.objects.get(id=pk)
   lead.delete()
   return redirect(f'/leads/')  

crm_leads/templates/crm_leads/lead_create.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'leads:lead-list' %}">Go back to leads list</a>
    <hr>
    <h1> Cretate a new lead</h1>
    <form method="post">
        {% csrf_token %} 
        {{ leadform.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

crm_leads/templates/crm_leads/lead_details.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'leads:lead-list' %}">Go back to leads list</a>
    <hr>
    <h1>The detail of {{ lead.first_name }} {{ lead.last_name }}</h1>
    <h2>Actual agent for this lead is {{ lead.agent }}</h2>
    <ul>
        <li>Age: {{ lead.age }}</li>
        <li>Source: {{ lead.source }}</li>
    </ul>
    <hr>
    <a href="{% url 'leads:update' lead.pk %}">Update lead info</a>
    <hr>
    <a href="{% url 'leads:delete' lead.pk %}">Delete lead info</a>
{% endblock content %}

crm_leads/templates/crm_leads/lead_list.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'leads:create' %}">Create a new lead</a>
    <hr>
    <h1>The list of leads</h1>
    {% for lead in leads %}
        <div>
            <a href="{% url 'leads:details' lead.pk %}">{{ lead.first_name }} {{ lead.last_name }}. Age:{{ lead.age }}</a>
        </div>
    {% endfor %}
{% endblock content %}

crm_leads/templates/crm_leads/lead_update.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'leads:details' lead.pk %}">Go back to lead detail</a>
    <hr>
    <h1> Update lead {{lead.first_name}} {{lead.last_name}}</h1>
    <form method="post" action=".">
        {% csrf_token %} 
        {{ leadform_update.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New lead</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>